#@ load("@ytt:data", "data")

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: #@ data.values.certmanager.namespace
  annotations:
    kapp.k14s.io/change-group: cert-manager
    kapp.k14s.io/change-rule: "delete after deleting tap"
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.1: certmanager-issuer-overlay
spec:
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: #@ str(data.values.certmanager.version)
  serviceAccountName: tap-install-gitops-sa
