#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  namespace: tap-install
  annotations:
    tekton.dev/git-0: #@ "https://" + data.values.git.basic_auth_host
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.git.basic_auth_username
  password: #@ data.values.git.basic_auth_password
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: git-creds
  namespace: tap-install
spec:
  toNamespaces:
  - '*'
