
apiVersion: v1
kind: Namespace
metadata:
  name: service-instances-mssql
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-claims-mssql
  labels:
    servicebinding.io/controller: "true"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: mssql
spec:
  description:
    short: It's an external reference to a Sql Server DB!
  pool:
    kind: secret
    labelSelector:
      matchLabels:
        service: "mssql"
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: mssql-cross-namespace
  namespace: service-instances-mssql
spec:
  consumingNamespaces:
  - '*'
  subject:
    group: ""
    kind: secret
    selector: # optional
      matchLabels:
        service: "mssql"
---
