#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cert-manager-config
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: cert-manager-config/app
    kapp.k14s.io/change-rule.1: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.2: "upsert after upserting contour" #! due to the certificatedelegation resource
    kapp.k14s.io/change-rule.3: "delete after deleting tap"
spec:
  serviceAccountName: tap-install-gitops-sa
  syncPeriod: 1m
  fetch:
  - git:
      url: #@ data.values.git.url
      ref: #@ data.values.git.ref
      secretRef:
        name: git-creds-carvel
  template:
  - ytt:
      paths:
      - clusters/full/app-contents/certs
      valuesFrom:
      - secretRef:
          name: tap-install-gitops
  deploy:
  - kapp: {}
