#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: mssql-instances
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: mssql-instances
    kapp.k14s.io/change-rule.2: "upsert after upserting tap"
    kapp.k14s.io/change-rule.3: "upsert after upserting mssql-as-a-service"
spec:
  serviceAccountName: tap-install-gitops-sa
  syncPeriod: 1m
  fetch:
  - git:
      url: #@ data.values.git.url
      ref: #@ data.values.git.ref
      secretRef:
        name: git-creds-carvel
  template:
  - ytt:
      paths:
      - clusters/full/app-contents/mssql-instances
      valuesFrom:
      - secretRef:
          name: tap-install-gitops
  deploy:
  - kapp: 
      intoNs: service-instances-mssql