#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-creds-carvel
  namespace: tap-install
  annotations:
    tekton.dev/git-0: #@ data.values.common.repos.http.host
    kapp.k14s.io/change-group: tap-install-gitops/rbac
    kapp.k14s.io/change-rule: "delete after deleting tap-install-gitops/app"
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.common.repos.http.basic_auth_username
  password: #@ data.values.common.repos.http.basic_auth_password
