#@ load("@ytt:data", "data")

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-creds
  annotations:
    tekton.dev/git-0: #@ "https://" + data.values.git.basic_auth_host
    kapp.k14s.io/change-rule: "delete after deleting tap"
spec:
  fromNamespace: tap-install
