
apiVersion: v1
kind: Namespace
metadata:
  name: service-instances-ad-run-as
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-claims-ad-run-as
  labels:
    servicebinding.io/controller: "true"
rules:
  - apiGroups: [""]
    resources: ["secrets"] #! Needs to be lower case and plural
    verbs: ["get", "list", "watch"]

---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: ad-run-as
spec:
  description:
    short: It's an external reference to an Active Directory server!
  pool:
    kind: Secret #! Needs to be singular with first letter capital
    labelSelector:
      matchLabels:
        service: "ad-run-as"
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: ad-run-as-cross-namespace
  namespace: service-instances-ad-run-as
spec:
  consumingNamespaces:
  - '*'
  subject:
    group: ""
    kind: Secret #! Needs to be singular with first letter capital
    selector:
      matchLabels:
        service: "ad-run-as"
---
