#@ load("@ytt:data", "data")

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: tap-install
spec:
  secretName: wildcard-cert-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  dnsNames:
  - #@ "*." + data.values.tap.domains.base
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: wildcard-cert-tls
  namespace: tap-install
spec:
  delegations:
    - secretName: wildcard-cert-tls
      targetNamespaces:
      - "*"
